[phases.setup]
nixPkgs = ['python313', 'gcc']

[phases.install]
cmds = [
  'curl -LsSf https://astral.sh/uv/install.sh | sh',
  'export PATH="$HOME/.local/bin:$PATH"',
  'uv sync --locked --no-dev'
]

[phases.build]
cmds = ['echo "no build phase needed"']

[start]
cmd = '$HOME/.local/bin/uv run alembic upgrade head && $HOME/.local/bin/uv run uvicorn reffie.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=\'*\''
